//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.createcontact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getVFCIOStream" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="getVFCFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getVFCIOStream",
    "getVFCFileName"
})
@XmlRootElement(name = "displayContactRequest")
public class DisplayContactRequest {

    @XmlElement(required = true)
    protected String getVFCIOStream;
    @XmlElement(required = true)
    protected String getVFCFileName;

    /**
     * Gets the value of the getVFCIOStream property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetVFCIOStream() {
        return getVFCIOStream;
    }

    /**
     * Sets the value of the getVFCIOStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetVFCIOStream(String value) {
        this.getVFCIOStream = value;
    }

    /**
     * Gets the value of the getVFCFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetVFCFileName() {
        return getVFCFileName;
    }

    /**
     * Sets the value of the getVFCFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetVFCFileName(String value) {
        this.getVFCFileName = value;
    }

}
