//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.createcontact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetFullContactDetail" type="{http://webmail.com/CreateContact}DisplayContact" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getFullContactDetail"
})
@XmlRootElement(name = "getFullContactDetailResponse")
public class GetFullContactDetailResponse {

    @XmlElement(name = "GetFullContactDetail")
    protected DisplayContact getFullContactDetail;

    /**
     * Gets the value of the getFullContactDetail property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayContact }
     *     
     */
    public DisplayContact getGetFullContactDetail() {
        return getFullContactDetail;
    }

    /**
     * Sets the value of the getFullContactDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayContact }
     *     
     */
    public void setGetFullContactDetail(DisplayContact value) {
        this.getFullContactDetail = value;
    }

}
