//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.folder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetWebmailSubFolderSubscribed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getWebmailSubFolderSubscribed"
})
@XmlRootElement(name = "getWebmailSubFolderSubscribedResponse")
public class GetWebmailSubFolderSubscribedResponse {

    @XmlElement(name = "GetWebmailSubFolderSubscribed")
    protected String getWebmailSubFolderSubscribed;

    /**
     * Gets the value of the getWebmailSubFolderSubscribed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetWebmailSubFolderSubscribed() {
        return getWebmailSubFolderSubscribed;
    }

    /**
     * Sets the value of the getWebmailSubFolderSubscribed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetWebmailSubFolderSubscribed(String value) {
        this.getWebmailSubFolderSubscribed = value;
    }

}
