//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.folder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.folder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.folder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedResponse }
     * 
     */
    public GetWebmailFolderSubscribedResponse createGetWebmailFolderSubscribedResponse() {
        return new GetWebmailFolderSubscribedResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedResponse }
     * 
     */
    public GetWebmailSubFolderSubscribedResponse createGetWebmailSubFolderSubscribedResponse() {
        return new GetWebmailSubFolderSubscribedResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedRequest }
     * 
     */
    public GetWebmailSubFolderSubscribedRequest createGetWebmailSubFolderSubscribedRequest() {
        return new GetWebmailSubFolderSubscribedRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderRequest }
     * 
     */
    public GetWebmailSubFolderRequest createGetWebmailSubFolderRequest() {
        return new GetWebmailSubFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedOtherRequest }
     * 
     */
    public GetWebmailFolderSubscribedOtherRequest createGetWebmailFolderSubscribedOtherRequest() {
        return new GetWebmailFolderSubscribedOtherRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderResponse }
     * 
     */
    public GetWebmailFolderResponse createGetWebmailFolderResponse() {
        return new GetWebmailFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailCreateFolderRequest }
     * 
     */
    public GetWebmailCreateFolderRequest createGetWebmailCreateFolderRequest() {
        return new GetWebmailCreateFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSubscriptionFolderResponse }
     * 
     */
    public GetWebmailSubscriptionFolderResponse createGetWebmailSubscriptionFolderResponse() {
        return new GetWebmailSubscriptionFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailFolderRequest }
     * 
     */
    public GetWebmailFolderRequest createGetWebmailFolderRequest() {
        return new GetWebmailFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedOtherResponse }
     * 
     */
    public GetWebmailFolderSubscribedOtherResponse createGetWebmailFolderSubscribedOtherResponse() {
        return new GetWebmailFolderSubscribedOtherResponse();
    }

    /**
     * Create an instance of {@link SubsFolderListReturn }
     * 
     */
    public SubsFolderListReturn createSubsFolderListReturn() {
        return new SubsFolderListReturn();
    }

    /**
     * Create an instance of {@link GetWebmailCreateFolderResponse }
     * 
     */
    public GetWebmailCreateFolderResponse createGetWebmailCreateFolderResponse() {
        return new GetWebmailCreateFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailDeleteFolderRequest }
     * 
     */
    public GetWebmailDeleteFolderRequest createGetWebmailDeleteFolderRequest() {
        return new GetWebmailDeleteFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderOtherResponse }
     * 
     */
    public GetWebmailFolderOtherResponse createGetWebmailFolderOtherResponse() {
        return new GetWebmailFolderOtherResponse();
    }

    /**
     * Create an instance of {@link MailFolderListReturn }
     * 
     */
    public MailFolderListReturn createMailFolderListReturn() {
        return new MailFolderListReturn();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedOtherRequest }
     * 
     */
    public GetWebmailSubFolderSubscribedOtherRequest createGetWebmailSubFolderSubscribedOtherRequest() {
        return new GetWebmailSubFolderSubscribedOtherRequest();
    }

    /**
     * Create an instance of {@link GetWebmailDeleteFolderResponse }
     * 
     */
    public GetWebmailDeleteFolderResponse createGetWebmailDeleteFolderResponse() {
        return new GetWebmailDeleteFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderResponse }
     * 
     */
    public GetWebmailSubFolderResponse createGetWebmailSubFolderResponse() {
        return new GetWebmailSubFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedOtherResponse }
     * 
     */
    public GetWebmailSubFolderSubscribedOtherResponse createGetWebmailSubFolderSubscribedOtherResponse() {
        return new GetWebmailSubFolderSubscribedOtherResponse();
    }

    /**
     * Create an instance of {@link SubsSubFolderListReturn }
     * 
     */
    public SubsSubFolderListReturn createSubsSubFolderListReturn() {
        return new SubsSubFolderListReturn();
    }

    /**
     * Create an instance of {@link GetWebmailFolderOtherRequest }
     * 
     */
    public GetWebmailFolderOtherRequest createGetWebmailFolderOtherRequest() {
        return new GetWebmailFolderOtherRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSubscriptionFolderRequest }
     * 
     */
    public GetWebmailSubscriptionFolderRequest createGetWebmailSubscriptionFolderRequest() {
        return new GetWebmailSubscriptionFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedRequest }
     * 
     */
    public GetWebmailFolderSubscribedRequest createGetWebmailFolderSubscribedRequest() {
        return new GetWebmailFolderSubscribedRequest();
    }

    /**
     * Create an instance of {@link SubsImapSubFolders }
     * 
     */
    public SubsImapSubFolders createSubsImapSubFolders() {
        return new SubsImapSubFolders();
    }

    /**
     * Create an instance of {@link SubsImapFolders }
     * 
     */
    public SubsImapFolders createSubsImapFolders() {
        return new SubsImapFolders();
    }

    /**
     * Create an instance of {@link ArrayOfSubsSubFolder }
     * 
     */
    public ArrayOfSubsSubFolder createArrayOfSubsSubFolder() {
        return new ArrayOfSubsSubFolder();
    }

    /**
     * Create an instance of {@link MailImapFolders }
     * 
     */
    public MailImapFolders createMailImapFolders() {
        return new MailImapFolders();
    }

    /**
     * Create an instance of {@link ArrayOfMailFolder }
     * 
     */
    public ArrayOfMailFolder createArrayOfMailFolder() {
        return new ArrayOfMailFolder();
    }

    /**
     * Create an instance of {@link ArrayOfSubsFolder }
     * 
     */
    public ArrayOfSubsFolder createArrayOfSubsFolder() {
        return new ArrayOfSubsFolder();
    }

}
