//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.edms.folder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edms.folder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edms.folder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFolderRequest }
     * 
     */
    public GetFolderRequest createGetFolderRequest() {
        return new GetFolderRequest();
    }

    /**
     * Create an instance of {@link HasChildRequest }
     * 
     */
    public HasChildRequest createHasChildRequest() {
        return new HasChildRequest();
    }

    /**
     * Create an instance of {@link HasChildResponse }
     * 
     */
    public HasChildResponse createHasChildResponse() {
        return new HasChildResponse();
    }

    /**
     * Create an instance of {@link GetFolderResponse }
     * 
     */
    public GetFolderResponse createGetFolderResponse() {
        return new GetFolderResponse();
    }

    /**
     * Create an instance of {@link FolderListReturn }
     * 
     */
    public FolderListReturn createFolderListReturn() {
        return new FolderListReturn();
    }

    /**
     * Create an instance of {@link Folder }
     * 
     */
    public Folder createFolder() {
        return new Folder();
    }

    /**
     * Create an instance of {@link ArrayOfFolders }
     * 
     */
    public ArrayOfFolders createArrayOfFolders() {
        return new ArrayOfFolders();
    }

}
