//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 02:35:33 PM IST 
//


package com.webmail.quota;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for webmailquota complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webmailquota">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QuotaLimit" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="QuotaUses" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "webmailquota", propOrder = {
    "quotaLimit",
    "quotaUses"
})
public class Webmailquota {

    @XmlElement(name = "QuotaLimit")
    protected long quotaLimit;
    @XmlElement(name = "QuotaUses")
    protected Long quotaUses;

    /**
     * Gets the value of the quotaLimit property.
     * 
     */
    public long getQuotaLimit() {
        return quotaLimit;
    }

    /**
     * Sets the value of the quotaLimit property.
     * 
     */
    public void setQuotaLimit(long value) {
        this.quotaLimit = value;
    }

    /**
     * Gets the value of the quotaUses property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuotaUses() {
        return quotaUses;
    }

    /**
     * Sets the value of the quotaUses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuotaUses(Long value) {
        this.quotaUses = value;
    }

}
