//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.ldapattribute;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.ldapattribute package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.ldapattribute
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLdapFNameResponse }
     * 
     */
    public GetLdapFNameResponse createGetLdapFNameResponse() {
        return new GetLdapFNameResponse();
    }

    /**
     * Create an instance of {@link GetLdapOneAttOtrUserResponse }
     * 
     */
    public GetLdapOneAttOtrUserResponse createGetLdapOneAttOtrUserResponse() {
        return new GetLdapOneAttOtrUserResponse();
    }

    /**
     * Create an instance of {@link GetContactDetailRequest }
     * 
     */
    public GetContactDetailRequest createGetContactDetailRequest() {
        return new GetContactDetailRequest();
    }

    /**
     * Create an instance of {@link GetVCFLdapDirResponse }
     * 
     */
    public GetVCFLdapDirResponse createGetVCFLdapDirResponse() {
        return new GetVCFLdapDirResponse();
    }

    /**
     * Create an instance of {@link VCFLdapDirListReturn }
     * 
     */
    public VCFLdapDirListReturn createVCFLdapDirListReturn() {
        return new VCFLdapDirListReturn();
    }

    /**
     * Create an instance of {@link GetLdapOneAttOtrUserRequest }
     * 
     */
    public GetLdapOneAttOtrUserRequest createGetLdapOneAttOtrUserRequest() {
        return new GetLdapOneAttOtrUserRequest();
    }

    /**
     * Create an instance of {@link GetContactDetailResponse }
     * 
     */
    public GetContactDetailResponse createGetContactDetailResponse() {
        return new GetContactDetailResponse();
    }

    /**
     * Create an instance of {@link ContactFullDetail }
     * 
     */
    public ContactFullDetail createContactFullDetail() {
        return new ContactFullDetail();
    }

    /**
     * Create an instance of {@link GetVCFLdapDirRequest }
     * 
     */
    public GetVCFLdapDirRequest createGetVCFLdapDirRequest() {
        return new GetVCFLdapDirRequest();
    }

    /**
     * Create an instance of {@link GetLdapFNameRequest }
     * 
     */
    public GetLdapFNameRequest createGetLdapFNameRequest() {
        return new GetLdapFNameRequest();
    }

    /**
     * Create an instance of {@link ArrayOfVCFLdapDir }
     * 
     */
    public ArrayOfVCFLdapDir createArrayOfVCFLdapDir() {
        return new ArrayOfVCFLdapDir();
    }

    /**
     * Create an instance of {@link VCFLdapDirAtt }
     * 
     */
    public VCFLdapDirAtt createVCFLdapDirAtt() {
        return new VCFLdapDirAtt();
    }

}
