//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.search;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetInboxMailSearchRequest }
     * 
     */
    public GetInboxMailSearchRequest createGetInboxMailSearchRequest() {
        return new GetInboxMailSearchRequest();
    }

    /**
     * Create an instance of {@link GetInboxMailQuickSearchRequest }
     * 
     */
    public GetInboxMailQuickSearchRequest createGetInboxMailQuickSearchRequest() {
        return new GetInboxMailQuickSearchRequest();
    }

    /**
     * Create an instance of {@link GetMailInboxQuickSearchResponse }
     * 
     */
    public GetMailInboxQuickSearchResponse createGetMailInboxQuickSearchResponse() {
        return new GetMailInboxQuickSearchResponse();
    }

    /**
     * Create an instance of {@link InboxListReturnQuickSearch }
     * 
     */
    public InboxListReturnQuickSearch createInboxListReturnQuickSearch() {
        return new InboxListReturnQuickSearch();
    }

    /**
     * Create an instance of {@link GetMailInboxSearchResponse }
     * 
     */
    public GetMailInboxSearchResponse createGetMailInboxSearchResponse() {
        return new GetMailInboxSearchResponse();
    }

    /**
     * Create an instance of {@link InboxListReturnSearch }
     * 
     */
    public InboxListReturnSearch createInboxListReturnSearch() {
        return new InboxListReturnSearch();
    }

    /**
     * Create an instance of {@link ArrayOfInboxMailSearch }
     * 
     */
    public ArrayOfInboxMailSearch createArrayOfInboxMailSearch() {
        return new ArrayOfInboxMailSearch();
    }

    /**
     * Create an instance of {@link ArrayOfInboxMailQuickSearch }
     * 
     */
    public ArrayOfInboxMailQuickSearch createArrayOfInboxMailQuickSearch() {
        return new ArrayOfInboxMailQuickSearch();
    }

    /**
     * Create an instance of {@link InboxQuickSearch }
     * 
     */
    public InboxQuickSearch createInboxQuickSearch() {
        return new InboxQuickSearch();
    }

    /**
     * Create an instance of {@link InboxSearch }
     * 
     */
    public InboxSearch createInboxSearch() {
        return new InboxSearch();
    }

}
