//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.inbox;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InboxListReturn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InboxListReturn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="InboxListReturn" type="{http://webmail.com/Inbox}ArrayOfInboxMail" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InboxListReturn", propOrder = {
    "success",
    "inboxListReturn"
})
public class InboxListReturn {

    @XmlElement(name = "Success")
    protected boolean success;
    @XmlElement(name = "InboxListReturn")
    protected ArrayOfInboxMail inboxListReturn;

    /**
     * Gets the value of the success property.
     * 
     */
    public boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     */
    public void setSuccess(boolean value) {
        this.success = value;
    }

    /**
     * Gets the value of the inboxListReturn property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInboxMail }
     *     
     */
    public ArrayOfInboxMail getInboxListReturn() {
        return inboxListReturn;
    }

    /**
     * Sets the value of the inboxListReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInboxMail }
     *     
     */
    public void setInboxListReturn(ArrayOfInboxMail value) {
        this.inboxListReturn = value;
    }

}
