//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.movetrash;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.movetrash package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.movetrash
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetWebmailSpamRequest }
     * 
     */
    public GetWebmailSpamRequest createGetWebmailSpamRequest() {
        return new GetWebmailSpamRequest();
    }

    /**
     * Create an instance of {@link GetWebmailMoveTrashResponse }
     * 
     */
    public GetWebmailMoveTrashResponse createGetWebmailMoveTrashResponse() {
        return new GetWebmailMoveTrashResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSpamResponse }
     * 
     */
    public GetWebmailSpamResponse createGetWebmailSpamResponse() {
        return new GetWebmailSpamResponse();
    }

    /**
     * Create an instance of {@link GetWebmailMoveTrashRequest }
     * 
     */
    public GetWebmailMoveTrashRequest createGetWebmailMoveTrashRequest() {
        return new GetWebmailMoveTrashRequest();
    }

}
