//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.compose;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.compose package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.compose
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetWebmailDeleteDraftRequest }
     * 
     */
    public GetWebmailDeleteDraftRequest createGetWebmailDeleteDraftRequest() {
        return new GetWebmailDeleteDraftRequest();
    }

    /**
     * Create an instance of {@link GetComposeMailResponse }
     * 
     */
    public GetComposeMailResponse createGetComposeMailResponse() {
        return new GetComposeMailResponse();
    }

    /**
     * Create an instance of {@link GetComposeMailRequest }
     * 
     */
    public GetComposeMailRequest createGetComposeMailRequest() {
        return new GetComposeMailRequest();
    }

    /**
     * Create an instance of {@link GetWebmailDeleteDraftResponse }
     * 
     */
    public GetWebmailDeleteDraftResponse createGetWebmailDeleteDraftResponse() {
        return new GetWebmailDeleteDraftResponse();
    }

    /**
     * Create an instance of {@link GetSaveMailDraftRequest }
     * 
     */
    public GetSaveMailDraftRequest createGetSaveMailDraftRequest() {
        return new GetSaveMailDraftRequest();
    }

    /**
     * Create an instance of {@link GetSaveMailDraftResponse }
     * 
     */
    public GetSaveMailDraftResponse createGetSaveMailDraftResponse() {
        return new GetSaveMailDraftResponse();
    }

}
