//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.ldapdirectory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getLdapDirectoryResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getLdapDirectoryResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DirUserListReturn" type="{http://webmail.com/LdapDirectory}ArrayOfUserDir" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getLdapDirectoryResponse", propOrder = {
    "dirUserListReturn"
})
public class GetLdapDirectoryResponse {

    @XmlElement(name = "DirUserListReturn")
    protected ArrayOfUserDir dirUserListReturn;

    /**
     * Gets the value of the dirUserListReturn property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfUserDir }
     *     
     */
    public ArrayOfUserDir getDirUserListReturn() {
        return dirUserListReturn;
    }

    /**
     * Sets the value of the dirUserListReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfUserDir }
     *     
     */
    public void setDirUserListReturn(ArrayOfUserDir value) {
        this.dirUserListReturn = value;
    }

}
