//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:55:47 PM IST 
//


package com.webmail.maildisplay;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.maildisplay package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.maildisplay
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMailDisplayResponse }
     * 
     */
    public GetMailDisplayResponse createGetMailDisplayResponse() {
        return new GetMailDisplayResponse();
    }

    /**
     * Create an instance of {@link InboxDisplay }
     * 
     */
    public InboxDisplay createInboxDisplay() {
        return new InboxDisplay();
    }

    /**
     * Create an instance of {@link GetMailDisplayRequest }
     * 
     */
    public GetMailDisplayRequest createGetMailDisplayRequest() {
        return new GetMailDisplayRequest();
    }

    /**
     * Create an instance of {@link GetMailHeaderResponse }
     * 
     */
    public GetMailHeaderResponse createGetMailHeaderResponse() {
        return new GetMailHeaderResponse();
    }

    /**
     * Create an instance of {@link GetMailHeaderRequest }
     * 
     */
    public GetMailHeaderRequest createGetMailHeaderRequest() {
        return new GetMailHeaderRequest();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

}
